### ISSUE TITLE
Fix error message in Todo items index view

### ISSUE THREAD

**Issue by Yorkshireman** [knopfler81/odot#2]
An error notification appears when clicking 'New Todo Item' on todo items index view:

![new_todo_item_error](https://cloud.githubusercontent.com/assets/8686588/17158468/7005107e-538e-11e6-81b3-c94b039b5634.png)

This is due to the fact that the `error_explanation` div in `views/todo_items/_form.html.erb` is not wrapped in a conditional. It is therefore always rendered whether or not there are any errors.

**Comment by Yorkshireman** [comment]
Hey dude! Really glad to see you've done some work on a branch and you are intending to fix the tests before merging it to the master branch! :-)

I've opened an Issue here that I've noticed. This is the general workflow we use at work:

1. Open an Issue,
2. When ready to work on, (a) assign yourself to the Issue (using the 'Assignees' feature on the right of this screen, (b) create a local branch with a similar name to the Issue title; in this case you might call the branch `2-fix-error-message-in-todo-items-view`,
3. Do the work on that branch,
4. Create a Pull Request with the branch when it's ready,
5. Other Devs review the work and merge it when they are happy for it to be committed to the master branch.

**Comment by Yorkshireman** [comment]
Take this on yourself or, if you want me to do it, I will.

**Comment by knopfler81** [comment]
Oh thanks for taking time again ! 😄 
I will try to fix this ! I didn't get the notification that you wrote to me :( I have to set my account I though I did it

**Comment by knopfler81** [comment]
I've just fixed the bug i'll let you check  
For the tests I would need your help please :)
